### ISSUE TITLE
Jest haste-map mock collisions from .next/standalone (6 suites fail at collection)

### ISSUE THREAD

**Issue by brlauuu** [brlauuu/podlog#750]
Running \`npx jest\` locally produces 6 failing test suites that never get to run their tests:

- \`tests/unit/ask-page-helpbox.test.tsx\`
- \`tests/unit/ask-page-rag-provider.test.tsx\`
- \`tests/unit/ask-page-play.test.tsx\`
- \`tests/unit/citations.test.tsx\`
- \`tests/unit/episode-chat-trigger-icon.test.tsx\`
- \`tests/unit/episode-chat.test.tsx\`

The error is:
\`\`\`
jest-haste-map: duplicate manual mock found: react-markdown
  * <rootDir>/__mocks__/react-markdown.tsx
  * <rootDir>/.next/standalone/__mocks__/react-markdown.tsx

Cannot find module './cjs/react-jsx-runtime.development.js' from '.next/standalone/node_modules/react/jsx-runtime.js'
\`\`\`

Cause: after a local \`npm run build\` the \`apps/web/.next/standalone/\` directory contains a copy of \`__mocks__/\` and \`node_modules/react/\` with a different shape than the canonical ones at the repo root. Jest's haste-map scans both and chokes on the duplication.

Pre-existing — fails on \`main\` too. Confirmed not caused by PR #745.

**Fix candidates:**
1. \`jest.config.js modulePathIgnorePatterns: ["<rootDir>/.next/"]\` to keep haste-map out of build artifacts.
2. \`watchPathIgnorePatterns\` similarly, plus \`testPathIgnorePatterns\` for completeness.
3. Always nuke \`.next/standalone\` before running tests locally (workaround, not a fix).

Option 1 is the right one. Should also unblock CI from running the affected suites (CI doesn't see this today because it does fresh builds with no leftover \`.next/standalone\`).
